language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y clang gcc-4.8 g++-4.8
  - sudo apt-get -y install libgsl0-dev libnlopt-dev libbpp-core-dev libbpp-seq-dev libbpp-phyl-dev
  - git submodule update --init --recursive
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar xvzf nlopt-2.4.2.tar.gz
  - cd nlopt-2.4.2
  - ./configure --prefix=/usr --enable-shared && make && sudo make install
  - cd ..
  - wget http://mirror.rise.ph/gnu/gsl/gsl-2.4.tar.gz
  - tar xvzf gsl-2.4.tar.gz
  - cd gsl-2.4
  - ./configure && make && sudo make install
  - cd ..
  - mkdir Release
  - cd Release
compiler:
  - clang
  - gcc
script:
  - cmake -DUSE_BEAGLE=OFF -DCMAKE_BUILD_TYPE=Release .. && make